### ISSUE TITLE
Paytrail new API

### ISSUE THREAD

**Issue by htukiain** [kunkku/django-oscar-paytrail#1]
This version of API will be depreciated by summer 2022.
New API spec is available at: https://docs.paytrail.com/#
Migration guide to new api: https://docs.paytrail.com/#/migration-guide

Happy to join testing and documenting the new API implementation.

**Comment by iqqmuT** [comment]
Pull request: #4 
@htukiain It would be great if you are able to test it!

**Comment by kunkku** [comment]
Released version 2.0.0, which uses the new API.
